variables:
  VER_MAJOR: "1" # MAJOR VERSION
  VER_MINOR: "0" # MINOR VERSION
  PATCH: "0"
  DESCRIPTION: "initial version"
  SCHEDULE_NAME: "RPA_robotsparebinindustries"
  SCHEDULE_SCRIPT: "curl --request POST 'https://api.github.com/repos/${GITHUB_REPOSITORY}/dispatches' -H 'Authorization: Bearer ${GITHUB_TOKEN}' -H 'Content-Type: application/json' --data '{\"event_type\": \"scheduled_run\"}'"
  SCHEDULE_PARAMETERS: "*/5 * * * *" # Run every 5 minutes
