# .github/workflows/main.yml
name: Orchestrator

on:
  workflow_dispatch: # Equivalent to GitLab's web trigger
  repository_dispatch: # Equivalent to GitLab's external trigger

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install flake8
        run: pip install flake8
        
      - name: Run flake8
        run: |
          echo "=== Running flake8 job === "
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --max-complexity=10 --max-line-length=170 --statistics

## Manual Approval Job
  approve:
    needs: test
    environment:
      name: approvers
    runs-on: ubuntu-latest
    steps:
    - name: manual approve
      run: |
          echo "Approved"

  release:
    needs: approve
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    outputs:
      SCHEDULE_NAME: ${{ steps.set_vars.outputs.SCHEDULE_NAME }}
      SCHEDULE_SCRIPT: ${{ steps.set_vars.outputs.SCHEDULE_SCRIPT }}
      SCHEDULE_PARAMETERS: ${{ steps.set_vars.outputs.SCHEDULE_PARAMETERS }}
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Load version
        run: |
          # Parse JSON and export variables
          echo "VER_MAJOR=$(jq -r '.VER_MAJOR' bot_config.json)" >> $GITHUB_ENV
          echo "VER_MINOR=$(jq -r '.VER_MINOR' bot_config.json)" >> $GITHUB_ENV
          echo "PATCH=$(jq -r '.PATCH' bot_config.json)" >> $GITHUB_ENV
          echo "DESCRIPTION=$(jq -r '.DESCRIPTION' bot_config.json)" >> $GITHUB_ENV
          echo "SCHEDULE_NAME=$(jq -r '.SCHEDULE_NAME' bot_config.json)" >> $GITHUB_ENV
          echo "SCHEDULE_SCRIPT=$(jq -r '.SCHEDULE_SCRIPT' bot_config.json)" >> $GITHUB_ENV
          echo "SCHEDULE_PARAMETERS=$(jq -r '.SCHEDULE_PARAMETERS' bot_config.json)" >> $GITHUB_ENV
         
      - name: Check and create release
        run: |
          echo "Checking release..."
          if ! gh release view "v$VER_MAJOR.$VER_MINOR.$PATCH" &>/dev/null; then
            echo "Release v$VER_MAJOR.$VER_MINOR.$PATCH not found"
            echo "Creating..."
            gh release create "v$VER_MAJOR.$VER_MINOR.$PATCH" --notes "$DESCRIPTION" --generate-notes
          fi
          echo "Release v$VER_MAJOR.$VER_MINOR.$PATCH already created."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Make sure the variables are clean without comments
          VER_MAJOR: ${{ env.VER_MAJOR }}
          VER_MINOR: ${{ env.VER_MINOR }}
          PATCH: ${{ env.PATCH }}
          DESCRIPTION: ${{ env.DESCRIPTION }}

      - name: Set outputs
        id: set_vars
        run: |
          echo "SCHEDULE_NAME=$SCHEDULE_NAME" >> $GITHUB_OUTPUT
          echo "SCHEDULE_SCRIPT=$SCHEDULE_SCRIPT" >> $GITHUB_OUTPUT
          echo "SCHEDULE_PARAMETERS=$SCHEDULE_PARAMETERS" >> $GITHUB_OUTPUT

  dev_run:
    needs: release
    runs-on: self-hosted
    if: github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4
      
      - name: Run in dev mode
        run: |
          cd bot
          chmod +x rcc
          ./rcc run --dev

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: robot-output
          path: robot/output/
          if-no-files-found: warn

  create_schedule:
    needs: [dev_run, release]
    runs-on: self-hosted
    if: github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4
      
      - name: Create schedule
        shell: bash
        run: |
          echo "Creating a schedule..."
          chmod +x $GITHUB_WORKSPACE/schedule.sh
          . $GITHUB_WORKSPACE/schedule.sh
          create_scheduled_task "$SCHEDULE_NAME" "$SCHEDULE_SCRIPT" "$SCHEDULE_PARAMETERS"
        env:
          SCHEDULE_NAME: ${{ needs.release.outputs.SCHEDULE_NAME }}
          SCHEDULE_SCRIPT: ${{ needs.release.outputs.SCHEDULE_SCRIPT }}
          SCHEDULE_PARAMETERS: ${{ needs.release.outputs.SCHEDULE_PARAMETERS }}

  ## Manual Approval Job
  # approveSchedule:
  #   needs: create_schedule
  #   environment:
  #     name: approvers
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: manual approve
  #     run: |
  #         echo "Approved"

  # delete_schedule:
  #   needs: approveSchedule
  #   runs-on: self-hosted
  #   if: github.event_name == 'workflow_dispatch'
  #   steps:
  #     - uses: actions/checkout@v4
      
  #     - name: Delete schedule
  #       shell: bash
  #       run: |
  #         echo "Deleting a schedule..."
  #         chmod +x $GITHUB_WORKSPACE/schedule.sh
  #         . $GITHUB_WORKSPACE/schedule.sh
  #         delete_scheduled_task "$SCHEDULE_NAME"
  #       env:
  #         SCHEDULE_NAME: $SCHEDULE_NAME 

  # run_schedule:
  #   needs: approveSchedule
  #   runs-on: self-hosted
  #   if: github.event_name == 'workflow_dispatch'
  #   steps:
  #     - uses: actions/checkout@v4
      
  #     - name: Run schedule
  #       shell: bash
  #       run: |
  #         echo "Running a schedule..."
  #         chmod +x $GITHUB_WORKSPACE/schedule.sh
  #         . $GITHUB_WORKSPACE/schedule.sh
  #         run_scheduled_task "$SCHEDULE_NAME"
  #       env:
  #         SCHEDULE_NAME: $SCHEDULE_NAME 

  # enable_schedule:
  #   needs: approveSchedule
  #   runs-on: self-hosted
  #   if: github.event_name == 'workflow_dispatch'
  #   steps:
  #     - uses: actions/checkout@v4
      
  #     - name: Enable schedule
  #       shell: bash
  #       run: |
  #         echo "Enabling a schedule..."
  #         chmod +x $GITHUB_WORKSPACE/schedule.sh
  #         . $GITHUB_WORKSPACE/schedule.sh
  #         enable_scheduled_task "$SCHEDULE_NAME"
  #       env:
  #         SCHEDULE_NAME: $SCHEDULE_NAME 

  # disable_schedule:
  #   needs: approveSchedule
  #   runs-on: self-hosted
  #   if: github.event_name == 'workflow_dispatch'
  #   steps:
  #     - uses: actions/checkout@v4
      
  #     - name: Disable schedule
  #       shell: bash
  #       run: |
  #         echo "Disabling a schedule..."
  #         chmod +x $GITHUB_WORKSPACE/schedule.sh
  #         . $GITHUB_WORKSPACE/schedule.sh
  #         disable_scheduled_task "$SCHEDULE_NAME"
  #       env:
  #         SCHEDULE_NAME: $SCHEDULE_NAME 

  # end_schedule:
  #   needs: approveSchedule
  #   runs-on: self-hosted
  #   if: github.event_name == 'workflow_dispatch'
  #   steps:
  #     - uses: actions/checkout@v4
      
  #     - name: Stop schedule
  #       shell: bash
  #       run: |
  #         echo "Stopping a schedule..."
  #         chmod +x $GITHUB_WORKSPACE/schedule.sh
  #         . $GITHUB_WORKSPACE/schedule.sh
  #         # Note: Linux doesn't need explicit task ending
  #         disable_scheduled_task "$SCHEDULE_NAME"
  #       env:
  #         SCHEDULE_NAME: $SCHEDULE_NAME 

  run:
    runs-on: self-hosted
    if: github.event_name == 'repository_dispatch'
    steps:
      - uses: actions/checkout@v4
      
      - name: Run in production
        run: |
          cd bot
          chmod +x rcc
          ./rcc run
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: robot-output
          path: robot/output/
          if-no-files-found: warn